// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Approximate token allocation across the latest model-visible request.
 */
export type ThreadContextUsage = { totalTokens: number, baseInstructionsTokens: number, toolDefinitionsTokens: number, userAndDeveloperTokens: number, assistantAndReasoningTokens: number, toolActivityTokens: number, otherTokens: number, };
